<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TakenLi</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.1.1</Version>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TakenLi.Core/TakenLi.Core.csproj" />
  </ItemGroup>
</Project>
